project:
  title: "TEC-IN5148"
  type: website
  output-dir: docs
editor: visual

website:
  title: "IN5148 Statistics and Data Science with Applications in Engineering"
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd
        text: Home

author: 
  - name: Alan R. Vazquez
    affiliations:
      - name: Department of Industrial Engineering
        
format:
  html:
    toc: true
    shift-heading-level-by: 1

  revealjs:
    output-ext: "slides.html"
    chalkboard: false
    multiplex: false
    footer: "Tecnologico de Monterrey"
    logo: IN5148_logo.png
    css: style.css
    slide-number: True


